/*
 * Copyright (c) 2022.
 *
 * Author (Fork): Pedro Aguiar
 * Original author: github.com/Grinderwolf/Slime-World-Manager
 *
 * Force, Inc (github.com/rede-force)
 */

/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "slimeworldmanager"
include(":slimeworldmanager-classmodifier")
include(":slimeworldmanager-api")
include(":slimeworldmanager-nms-common")
include(":slimeworldmanager-nms-v1_8_R3")
include(":slimeworldmanager-plugin")
include(":slimeworldmanager-importer")
